### ISSUE TITLE
Thanks & please publish in NC app store

### ISSUE THREAD

**Issue by poVoq** [lojewskimarcin/user_sql#1]
Just wanted to say thanks for updating this important app for NC 11 & 12!

Any plans for putting the updated version on the NC appstore again?

**Comment by lojewskimarcin** [comment]
I'm not author of this app so I cannot update it in the appstore.

You can always download my version of the app from:
https://github.com/lojewskimarcin/user_sql/archive/v2.3.1-nc11.tar.gz
https://github.com/lojewskimarcin/user_sql/archive/v2.3.1.1-nc12.tar.gz
