### ISSUE TITLE
Gets stuck "saving..." or "verifying..."

### ISSUE THREAD

**Issue by poVoq** [lojewskimarcin/user_sql#2]
I am trying to integrate my Wordpress Mysql user database with NC12 (uses postgresql). According to the original documentation this should work with the Joomla phpass encryption.
However, with the recent v2.3.1.1-nc12 release I seem to not even get that far. When I put in the needed Mysql details and press "save" or "verify" it just shows the respective purple bar at the bottom indefinitely and never actually saves the settings. 

Any idea what could be causing this? I am also authenticating a Dokuwiki against the same WP database (with this: https://www.dokuwiki.org/plugin:authwordpress ) so the problem is likely on the Nextcloud side of things.

Thanks a lot for any help.

**Comment by poVoq** [comment]
Looking at the webconsole, it throws an 500 Internal server error on "user_sql/ajax/settings.php" if that helps.

**Comment by poVoq** [comment]
Probably an error caused by me trying to use it on a shared host (OVH). Any way to disable the not really needed AJAX functionality as a fallback mode?

**Comment by Aaider** [comment]
Hello,

I'm having similar problem. I've had this working in OC9 and now trying to port to NC12. Following errors that probably has something to do with this:

```
Call to a member function getValue() on null at /var/www/nextcloud/lib/private/DB/ConnectionFactory.php#81
Undefined variable: systemConfig at /var/www/nextcloud/lib/private/DB/ConnectionFactory.php#80
Argument 1 passed to OC\DB\ConnectionFactory::__construct() must be an instance of OC\SystemConfig, none given, called in /var/www/nextcloud/apps/user_sql/ajax/settings.php on line 162 and defined at /var/www/nextcloud/lib/private/DB/ConnectionFactory.php
Failed to connect to the database: Unsupported type: 
```

**Comment by poVoq** [comment]
Interesting reply with an actual error message (might be related):

> Call to a member function getValue() on null at /var/www/nextcloud/lib/private/DB/ConnectionFactory.php#81
> Undefined variable: systemConfig at /var/www/nextcloud/lib/private/DB/ConnectionFactory.php#80
> Argument 1 passed to OC\DB\ConnectionFactory::__construct() must be an instance of OC\SystemConfig, none given, called in /var/www/nextcloud/apps/user_sql/ajax/settings.php on line 162 and defined at /var/www/nextcloud/lib/private/DB/ConnectionFactory.php
> Failed to connect to the database: Unsupported type:

**Comment by poVoq** [comment]
https://github.com/lojewskimarcin/user_sql/pull/4

might have fixed it, will check later.
